# Generated by Django 3.1 on 2021-01-19 03:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('layover', models.BooleanField(default=False)),
                ('crew', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
